### ISSUE TITLE
Java example for generating Tree Hash does not work

### ISSUE THREAD

**Issue by gurka** [awsdocs/amazon-glacier-developer-guide#19]
The Java example at https://github.com/awsdocs/amazon-glacier-developer-guide/blob/master/doc_source/checksum-calculations.md contains a bug in `getChunkSHA256Hashes`. The `offset` variable is misused when reading from the `fileStream` into the `buff` buffer. As soon as you try to hash a file larger than one chunk size (1MiB) it will thrown an `IndexOutOfBounds` exception:

```
Exception in thread "main" java.lang.IndexOutOfBoundsException
        at java.base/java.io.FileInputStream.readBytes(Native Method)
        at java.base/java.io.FileInputStream.read(FileInputStream.java:279)
        at TreeHashExample.getChunkSHA256Hashes(TreeHashExample.java:97)
        at TreeHashExample.computeSHA256TreeHash(TreeHashExample.java:56)
        at TreeHashExample.main(TreeHashExample.java:28)
```

Removing the `offset` variable and changing the while-loop to:
```
            while ((bytesRead = fileStream.readNBytes(buff, 0, ONE_MB)) > 0) {
                md.reset();
                md.update(buff, 0, bytesRead);
                chunkSHA256Hashes[idx++] = md.digest();
            }
```

will make it work correctly.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
